### ISSUE TITLE
why it says "No config.clj file at . "?

### ISSUE THREAD

**Issue by luckypoem** [samrat/ecstatic#1]
hi.
as3:~/ecstatic-site/mysite/src# lein run --src . --output export
WARNING: You're currently running as root; probably by accident.
Press control-C to abort or Enter to continue as root.
Set LEIN_ROOT to disable this warning.
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
Loading custom code...
Preparing directory structure...
Finding updated posts and pages...
Generating main feed...
error - No config.clj file at .
as3:~/ecstatic-site/mysite/src# ls
code  config.clj  pages  posts  resources  snippets  templates
as3:~/ecstatic-site/mysite/src#

u can see clearly there is config.clj file in ~/ecstatic-site/mysite/src/ dir,why it says "No config.clj file at . "?

how to fix it?
tks

**Comment by samrat** [comment]
Hi there,

Could you let me know what config.clj contains?

The format for config.clj is at http://samrat.me/ecstatic/ (see section
Setup and Configuration).
The error message might have been a bit misleading and I'll change it soon.

Let me know if that solves your problem.

-- Samrat

**Comment by luckypoem** [comment]
hi.
as3:~/ecstatic-site/mysite/src# ls
code  config.clj  pages  posts  resources  snippets  templates
as3:~/ecstatic-site/mysite/src# cat config.clj
{:site-url "http://es.brite.biz.st",
 :site-name "My Ecstatic Site",
 :site-author "ym",
 :site-description "check it!"}
as3:~/ecstatic-site/mysite/src#

is the format of my config.clj file correct?
tks

**Comment by samrat** [comment]
It looks correct. Are you still getting this problem?

Could you try using the absolute path instead: ecstatic -s `pwd` -o export ?

You could also create a new site using ecstatic itself: `ecstatic --new
mysite`.

-- Samrat

**Comment by luckypoem** [comment]
hi.
i feel strange that i can't use "lein bin" to generate executable.i don't know why.is it becoz ur app is incompatible with java 8.0??
as3:~/ecstatic-site# lein bin
WARNING: You're currently running as root; probably by accident.
Press control-C to abort or Enter to continue as root.
Set LEIN_ROOT to disable this warning.
Java HotSpot(TM) Client VM warning: TieredCompilation is disabled in this release.
'bin' is not a task. See 'lein help'.
Did you mean this?
         run
as3:~/ecstatic-site#
as3:~/ecstatic-site# java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) Client VM (build 25.5-b02, mixed mode)
as3:~/ecstatic-site#

**Comment by samrat** [comment]
Java 8 is not the problem. You need to add lein-bin to your profiles.clj
file in ~/.lein/profiles.clj( See https://github.com/raynes/lein-bin#usage)

**Comment by luckypoem** [comment]
hi.
could u pls upload the generated executable file:ecstatic to github?
tks a lot

**Comment by samrat** [comment]
As the file is a binary and with all the dependencies the file size gets
quite large, I prefer not to put it in git. I could, however email it to
you.

If you want me to email you the executable, you can email me or reply here
with your email address. My email address is samrat@samrat.me

**Comment by luckypoem** [comment]
hi.
my email address:luckypoem#gmail.com,
tks.

**Comment by samrat** [comment]
Sent. Let me know if you face any more problems.

**Comment by luckypoem** [comment]
hi.
u said "You need to add lein-bin to your profiles.clj file in ~/.lein/profiles.clj",but
as3:~# cd ~/.lein/
as3:~/.lein# ls
repl-history  self-installs
as3:~/.lein# find . -name profiles.clj
as3:~/.lein#

there is no profiles.clj in ~/.lein/,why?how to fix it?
tks

**Comment by luckypoem** [comment]
hi.
i uploaded ecstatic file,now the blog is setup successfully: http://es.brite.biz.st/ ,but how to paginate?
and can u upload ecstatic file to some webdisk for others to download?
tks a lot

**Comment by samrat** [comment]
Glad that you got it working. There is no pagination support yet, but you can limit the number of posts show in the home page and display the rest of the posts in your Archives page.

Also, did you have to make any changes to config.clj. I just want to figure out what went wrong with that.

I'll try figuring out some place to upload the ecstatic binary.

Thanks.

**Comment by luckypoem** [comment]
hi.
i uploaded to here: https://googledrive.com/host/0B1CmeJlGMtoLZGFYU3RRY1hldnc/ecstatic ,u can update ur readme.md with this url,

**Comment by luckypoem** [comment]
hi.
i met a strange issue.
as3:~/ecstatic-site/mysite# git clone https://github.com/samrat/samrat.github.com samrat.github.com-site
as3:~/ecstatic-site/mysite# cd samrat.github.com-site
as3:~/ecstatic-site/mysite/samrat.github.com-site# ls
archives  ecstatic                     happychart.png  resources
blog      favicon.ico                  images          samrat-pubkey.asc
books     feeds                        index.html      src
CNAME     google1273dd2fbfcd9338.html  projects        tags
as3:~/ecstatic-site/mysite/samrat.github.com-site# nohup Rwebserver 39846 > /dev/null &

then i visit http://as3.brite.biz:39846/,it's accessible.and i bound my domain:es2.brite.biz.st to the dir:
~/ecstatic-site/mysite/samrat.github.com-site/,then i visit http://es2.brite.biz.st/index.html or 
http://es2.brite.biz.st ,nothing shows,why? another site: http://es.brite.biz.st/ is ok.
how to fix it?
